### ISSUE TITLE
Automate Salesbot to tag rep in tenant ops

### ISSUE THREAD

**Issue by jfletchersimpson** [TheConnMan/salesbot#4]
Need to tag trial tenant element with sales rep name when the Salesbot app assigns user "You're up".
- For the horn or magnet
- Tag name/value = Sales:<rep name>
- https://api.app.metricly.com/swagger-ui.html#!/elements/createElementTagUsingPOST

Note: We have a new feature to include the tenant ID during signup.  You might need that to figure out the element ID.

**Comment by TheConnMan** [comment]
This is well outside the scope of this project. I don't want to tie this project to a particular use case or API outside of Slack.

**Comment by jfletchersimpson** [comment]
Well fine.
